### PR TITLE
Make Travis test all supported Python versions

### PR DESCRIPTION
**Pull request by mgedmin**
Also fixes test failure on 2.6 after #11 got merged.

### CODE REVIEW

**Comment by mgedmin** [comment]
I guess #13 also fixes this, but it also makes changes to tests under Python 3.4 that I don't feel qualified to review.

**Comment by tseaver** [comment]
My bad -- I just jammed in a fix without looking for yours.

**Comment by mgedmin** [comment]
Heh, I basically did the same -- noticed #13 when it came in, forgot about it when @agroszer complained about Python 2.6 breakage.

**Comment by jamadden** [comment]
Sorry about that everyone, my fault.

**Comment by mgedmin** [comment]
None of the reviewers noticed that tox.ini and .travis.yml got out of sync.  Our fault.  :)

**Pull request closed without merging**
