### PR TITLE
Config with c code

### PR DESCRIPTION
**Pull request by icemac**
* Lint the code.
* Add support for Python 3.9.

Uses https://github.com/zopefoundation/meta/pull/114

### CODE REVIEW

**Comment by icemac** [comment]
Just for `manylinux2014_aarch64` the tests fail with `ModuleNotFoundError: No module named 'test'`. 
This is strange – doesn't the container have a complete Python installation? It seems that the missing `test` module is the one which belongs to the stdlib.
Any ideas how to add the missing module for the tests?

**Comment by jamadden** [comment]
On Debian, you would install the `libpythonX.Y-testsuite` package; on Ubuntu, you would `apt-get pythonX.Y-full` (IIRC). 

But here, there's no package manager in use. The Python installs are built from source directly into the docker image, and then they sadly [remove the test package](https://github.com/pypa/manylinux/blob/347adcae7f9402ad088c9e72fbbe8204910e5db3/docker/build_scripts/build-cpython.sh#L51). 

The only way I can think to get it back is to download the Python source tarball, unzip it, and either move the `Lib/test` directory into the installation, or add `Lib/` to the `PYTHONPATH`.

**Comment by jamadden** [comment]
This was done to [make the image smaller](https://github.com/pypa/manylinux/commit/a707f7c1e1af4ba02edb6877028f7c504003dad8). The Python 3.9 `test` directory takes about 10MB (uncompressed) on my disk, but I'm guessing its highly compressible. We could try raising an issue asking for the `test` directory to be left in...

**Comment by icemac** [comment]
@jamadden Thank you for your analysis. I created https://github.com/pypa/manylinux/issues/1142 and I am willing to wait for comments over there before starting to change this PR here.

**Comment by pfw** [comment]
I'm in the process of testing an app with 3.10 and was thinking about how to go forward given this block on manylinux not having test_support. The bits that test_pickle uses seem relatively contained, would it make sense to just pull in those pieces for the moment? I'm happy to have a look at getting that going if it sounds like it might be workable.

**Comment by icemac** [comment]
@pfw wrote:
> just pull in those pieces for the moment

What do you mean here? I do no understand what you are suggesting to do.

**Comment by pfw** [comment]
@icemac I was having a poke through the cpython source for the test module and the functions used to see if it makes sense to just pull those locally into this repo - there is some precedent for this with the _pickle_33.c file.  It looks like there isn't much used. My motivation was to jump past the block on test builds if that is holding up a 3.9/3.10 compatible release.

**Comment by icemac** [comment]
An alternative idea would be to skip the tests needing the `test` package if it cannot be imported.

**Comment by icemac** [comment]
https://github.com/pypa/manylinux/issues/1142 was resolved the way I asked for, so the tests are now green. @mgedmin or @jamadden could one of you please review this PR, so we can see that Python 3.10 support works in #61?

**Comment by pfw** [comment]
Great!

**Review by jamadden — APPROVED** [review]
I have theoretical concerns about the "lint the code" step. This code was essentially "branched" from the standard library to add support for `binary`. It might be easier to include updates from after the branching (e.g., pickle protocol 4, #21) if we avoided non-functional changes like linting. But perhaps that ship has sailed…

Otherwise, LGTM.

ETA: Also, I suspect the linting will make it more difficult to merge other open PRs like #61. Looks like a lot of manual rebasing/merging.

**Comment by icemac** [comment]
@jamadden I undid the flake8 changes. This makes the diff smaller and should not hurt.

**Comment by icemac** [comment]
Thank you for reviewing this PR. 😃

Released as https://pypi.org/project/zodbpickle/2.1.0/#files

**Pull request merged**
