### PR TITLE
Configuring for c-code

### PR DESCRIPTION
**Pull request by tseaver**

### CODE REVIEW

**Comment by tseaver** [comment]
@dataflake, @icemac Any idea about the skipped-but-required tests here?

I could just remove them from the branch protection, but maybe there is policy for applying such changes uniformly across the organization?

**Comment by dataflake** [comment]
I have fixed those manually usually. When you run the configure script there's a step at the end that does this, though.

**Review by icemac — APPROVED** [review]

**Comment by icemac** [comment]
> I have fixed those manually usually. When you run the configure script there's a step at the end that does this, though.

Even though this script might have a bug: It should keep the setting of required code reviews for pull requests but seems to set them always. – I think we did not have a discussion for which packages (or even all) code reviews should be required.

**Comment by dataflake** [comment]
IMHO the setting of "always require reviews, but these groups (owners, managers, release managers) are exempt" is good for all packages.

**Pull request merged**
