### PR TITLE
Fix Python version on description

### PR DESCRIPTION
**Pull request by acr929**
Change "_description='Fork of Python  **3** pickle module.'_" to "_description='Fork of Python **2** pickle module.'_" on _setup.py_

### CODE REVIEW

**Comment by mgedmin** [comment]
We actually have embedded copies of _pickle.c from both Python 2 and Python 3. Maybe let's just drop the Python version entirely from the description?

**Comment by tseaver** [comment]
@mgedmin

> We actually have embedded copies of _pickle.c from both Python 2 and Python 3. Maybe let's just drop the Python version entirely from the description?

Or note that we fork both versions, and add something to the README / long description explaining why we have both?

**Comment by icemac** [comment]
The README already tells about the two forks.

**Comment by icemac** [comment]
Thank you.

**Pull request merged**
