### PR TITLE
Support py3.9 and above.

### PR DESCRIPTION
**Pull request by pfw**
I'd really like to add this as something between a comment on an issue and a pull request as my C skills are quite rusty and although it builds and all the tests pass it should really be looked over closely.

The changes for _PyObject_LookupAttrId came from here: https://github.com/python/cpython/commit/98c4433a81a4cd88c7438adbee1f2aa486188ca3

Py_Size(x) = y to Py_SET_SIZE(x, y) and  _PyObject_HasAttrId to _PyObject_LookupAttrId

### CODE REVIEW

**Comment by pfw** [comment]
Sorry I messed up on 3.9, I'll fix that up.

**Comment by pfw** [comment]
I'll leave this open for the moment but although it works on 3.9 and 3.10 it fails to build on versions below... I'll see if I can figure out how to support both but might be running into limits of C skills.

**Comment by jamadden** [comment]
Thanks for this PR! I've opened #61 to restore support for older versions of Python.

**Comment by pfw** [comment]
Good one, thanks.

**Pull request closed without merging**
