### PR TITLE
Add support for Python 3.8, drop support for Python 2.7.

### PR DESCRIPTION
**Pull request by icemac**
See #48

### CODE REVIEW

**Comment by mgedmin** [comment]
Heh, I did an entire code review without noticing the "Drop Python 2.7" typo in the PR title/commit message.

When I finally noticed it was a bit of a shock -- it's not 2020 yet. :)

**Comment by jamadden** [comment]
All the files (e.g., `_pickle2.c`) and code (e.g., `if sys.version_info[0] >= 3:`) for Python 2.7 are still here. Maybe we can restore claiming support for it?

**Comment by mgedmin** [comment]
There's nothing to restore because nothing was dropped.  The only error is in metadata (git commit message).  I don't think it's worth the hassle of a rebase and force-pushing to master.

**Comment by icemac** [comment]
Puh, only a typo in the PR title.

**Comment by icemac** [comment]
And in the commit message which is now on master. … In about half a year I'll actually drop Python 2 support. 😁

**Pull request merged**
